### ISSUE TITLE
Appairage station

### ISSUE THREAD

**Issue by Crakett** [GwendalT35/WMR500_local#1]
Je possède une station wmr500 et je commence juste à travailler sur l'envoi des données de connexion wifi de la station. J'ai 3 pistes :
- Analyse réseau (wireshark)
- décompiler APK SmartLiving WMR500
- Ouverture station pour lire et modifier les mémoires eeprom (je l'ai déjà ouverte pour mettre en permanent l'éclairage afficheur)
Mon but final est de récupérer les infos envoyés en MQTT par la station directement dans le mosquito de jeedom.

**Comment by GwendalT35** [comment]
La station météo utilise l'ip "mqtt.idtlive.com" sur le port 1883 (mqtt).  Je ne connais pas jeedom, cependant si la station est déjà appairer à un réseau, il faut faire du DNSspooffing vers votre broker mqtt (mosquitto dans votre cas j'imagine).

Ensuite les commandes que l'on peut utiliser pour récuper les données sont :

sub: enno/out/UUID_De_La_Station

pub: {"command":"getChannelXStatus","id":"UUID_De_La_Station"}
Ou 'X' représente le channel sur lequel est appairé la station météo à la console météo (1, 2 ou 3).

J'espère que cela vous donnes un début de piste pour votre projet. Si vous avez d'autre question, n'hésitez pas !

**Comment by Crakett** [comment]
Merci pour les infos. Malheureusement ma station n'est pas appairé avec mon wifi. Cette étape est primordiale aux autres. Et malheureusement oregon impose d'être connecté dans son appli pour pouvoir ajouter une station (et lui mettre les infos wifi ssid et password). Je continu mes investigations.

**Comment by GwendalT35** [comment]
J'vous upload le programme pour appairer la station météo.

**Comment by Crakett** [comment]
Super merci je regarde ça ce soir et vous tiens au courant.

**Comment by GwendalT35** [comment]
Pas de soucis, voici le RAR [client_appairage_WMR500](https://github.com/GwendalT35/WMR500_local/releases/tag/1.0.0).
N'oubliez pas de vous connecter au réseau de la station avec SSID du type "**OS_WMR_XXXX**"

**Comment by Crakett** [comment]
un grand merci pour votre utilitaire, j'ai pu associer la station. reste le DNSspooffing pour renvoyer le MQTT vers mon broker mosquito de mon raspberry domotique jeedom. merci pour l'aide.
